#!/bin/bash

./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt


./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cpuSetQS_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
