#!/bin/bash

./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt


./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSetQS_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
