#!/bin/bash

./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt

./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt

./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt

./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt

./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt


./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt

./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt

./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt

./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt

./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./cpuSH_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
