#!/bin/bash

./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt


./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./cgSH_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
