#!/bin/bash

./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt


./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./nclSQS A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
