#!/bin/bash

./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt

./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt

./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt

./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt

./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt


./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt

./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt

./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt

./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt

./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
./gpuSH_LocalMem_OpenCL A C AG CC ACC AAA ATTA ACCA AGTAG CGTAG CGGCAT AGGCAT CGAAAAA TTACATA GAACATTT ACCCTTAG ATCATATCT TTAATGACA GAACTCTCAG AAAAAAAAAA dna13.txt
