#!/bin/bash

./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt


./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt

./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
./gpuSH_LocalMem_OpenCL A AG ACC ATTA AGTAG CGGCAT CGAAAAA GAACATTT ATCATATCT GAACTCTCAG dna13.txt
